# Generated by Django 5.2.5 on 2026-04-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
