# Generated by Django 5.2.5 on 2026-04-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_alter_plan_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='products/sources/'),
        ),
    ]
