# Generated by Django 5.2.5 on 2026-04-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_category_slug_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer', 'Chuyển khoản ngân hàng')], default='Bank Transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Chờ thanh toán'), ('Paid', 'Đã thanh toán')], default='Pending', max_length=20),
        ),
    ]
