# Generated by Django 5.2.5 on 2026-04-06 12:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_order_payment_method_order_payment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('Percentage', 'Phần trăm (%)'), ('Fixed', 'Số tiền cố định ($)')], default='Percentage', max_length=20)),
                ('discount_value', models.FloatField()),
                ('min_purchase', models.FloatField(default=0.0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
                ('usage_limit', models.IntegerField(default=100)),
                ('used_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer', 'Chuyển khoản ngân hàng'), ('Momo', 'Ví điện tử Momo'), ('ZaloPay', 'Ví điện tử ZaloPay')], default='Bank Transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ thanh toán'), ('Paid', 'Đã thanh toán'), ('Processing', 'Đang xử lý'), ('Completed', 'Hoàn thành'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.coupon'),
        ),
        migrations.CreateModel(
            name='ProductKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_data', models.TextField(help_text='Định dạng: account:password hoặc license_key')),
                ('is_sold', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_keys', to='shops.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='shops.product')),
            ],
        ),
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Chuyển khoản ngân hàng'), ('Momo', 'Ví MoMo'), ('ZaloPay', 'Ví ZaloPay'), ('VNPAY', 'Cổng VNPAY')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Chờ thanh toán'), ('Completed', 'Đã nạp tiền'), ('Expired', 'Hết hạn'), ('Failed', 'Thất bại')], default='Pending', max_length=20)),
                ('note', models.CharField(max_length=100, unique=True)),
                ('qr_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('Deposit', 'Nạp tiền'), ('Payment', 'Thanh toán'), ('Refund', 'Hoàn tiền')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Đang xử lý'), ('Completed', 'Thành công'), ('Failed', 'Thất bại')], default='Pending', max_length=20)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
