# Generated by Django 5.2.5 on 2026-04-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_coupon_order_discount_amount_order_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='TopUpRequest',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
