# Generated by Django 6.0.2 on 2026-04-07 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_downloadgrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloadgrant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
