# Generated by Django 5.2.5 on 2026-04-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_alter_downloadgrant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
