# Generated by Django 5.2.5 on 2026-04-06 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_fullname_profile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Bank Transfer', 'Chuyển khoản ngân hàng'), ('Momo', 'Ví MoMo'), ('ZaloPay', 'Ví ZaloPay'), ('VNPAY', 'Cổng VNPAY')], max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Chờ thanh toán'), ('Completed', 'Đã nạp tiền'), ('Expired', 'Hết hạn'), ('Failed', 'Thất bại')], default='Pending', max_length=20)),
                ('note', models.CharField(max_length=100, unique=True)),
                ('qr_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('Deposit', 'Nạp tiền'), ('Payment', 'Thanh toán'), ('Refund', 'Hoàn tiền')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Đang xử lý'), ('Completed', 'Thành công'), ('Failed', 'Thất bại')], default='Pending', max_length=20)),
                ('method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
