# Generated by Django 5.2.5 on 2026-04-08 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_balance_alter_topuprequest_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteMusic',
        ),
    ]
