# Generated by ChatGPT on 2026-04-02
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
            options={
                'unique_together': {('page', 'key')},
            },
        ),
    ]
