# Generated by ChatGPT on 2026-04-02
from django.db import migrations


def seed_contact(apps, schema_editor):
    ContentBlock = apps.get_model('core', 'ContentBlock')

    defaults = [
        ("contact", "title", "Liên hệ | Nexora"),
        ("contact", "hero_title", "Liên hệ với chúng tôi"),
        ("contact", "hero_subtitle", "Chúng tôi luôn sẵn sàng lắng nghe bạn. Dù bạn có thắc mắc về tính năng, giá cả hay bất cứ điều gì khác, đội ngũ của chúng tôi luôn sẵn lòng giải đáp."),
        ("contact", "form_name_label", "Họ và tên"),
        ("contact", "form_name_placeholder", "Nhập họ và tên của bạn"),
        ("contact", "form_email_label", "Email"),
        ("contact", "form_email_placeholder", "you@example.com"),
        ("contact", "form_phone_label", "Số điện thoại"),
        ("contact", "form_phone_placeholder", "Nhập số điện thoại"),
        ("contact", "form_package_label", "Gói dịch vụ đăng ký"),
        ("contact", "form_package_1", "Gói Basic"),
        ("contact", "form_package_2", "Gói Standard"),
        ("contact", "form_package_3", "Gói Premium"),
        ("contact", "form_message_label", "Ghi chú"),
        ("contact", "form_message_placeholder", "Nhu cầu của bạn là gì?"),
        ("contact", "form_submit", "Gửi yêu cầu"),
        ("contact", "info_address_title", "Địa chỉ"),
        ("contact", "info_address_value", "Căn 3.04 Tầng 3 Khu Thương mại – Dịch Vụ – Văn phòng – Officetel, Số 38 Trương Quốc Dung, P. Phú Nhuận, TP Hồ Chí Minh, Việt Nam"),
        ("contact", "info_phone_title", "Số điện thoại"),
        ("contact", "info_phone_value", "+84 764552008 (Thứ 2 - Thứ 6: 9h - 18h)"),
        ("contact", "info_email_title", "Email liên hệ"),
        ("contact", "info_email_value", "hotro.ipsystem@gmail.com"),
        ("contact", "info_follow_title", "Theo dõi"),
        ("contact", "info_facebook_url", "https://www.facebook.com"),
        ("contact", "info_zalo_url", "https://zalo.me"),
        ("contact", "info_linkedin_url", "https://www.linkedin.com"),
    ]

    for page, key, content in defaults:
        ContentBlock.objects.update_or_create(
            page=page,
            key=key,
            defaults={"content": content},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_content"),
    ]

    operations = [
        migrations.RunPython(seed_contact),
    ]
