# Generated by ChatGPT on 2026-04-02
from django.db import migrations


def seed_contact_map(apps, schema_editor):
    ContentBlock = apps.get_model('core', 'ContentBlock')

    defaults = [
        ("contact", "map_title", "Bản đồ"),
        (
            "contact",
            "map_embed",
            '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d979.7682139057952!2d106.62783722848133!3d10.80573201665651!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752b005c33e53b%3A0x13e182affd655971!2sK-BOX%20Coffee%2024%2F24!5e0!3m2!1svi!2s!4v1775112683805!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
        ),
    ]

    for page, key, content in defaults:
        ContentBlock.objects.update_or_create(
            page=page,
            key=key,
            defaults={"content": content},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_seed_contact"),
    ]

    operations = [
        migrations.RunPython(seed_contact_map),
    ]
